#!/bin/bash
cat /proc/sys/kernel/hostname >> PCinfo.txt
cat /proc/cpuinfo | grep processor | wc -l >> PCinfo.txt
cat /proc/meminfo | grep MemTotal >> PCinfo.txt
cat /proc/meminfo | grep MemFree >> PCinfo.txt
echo ---------------------------------------- >> PCinfo.txt
